/*  Copyright 2018 Affonso Amendola
    
    This file is part of Wumpus3D.

    Wumpus3D is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Wumpus3D is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Wumpus3D.  If not, see <https://www.gnu.org/licenses/>
*/

#ifndef W3D_H
#define W3D_H

#define cart_x 0
#define cart_y 1
#define cart_z 2

float * world_to_screen_coordinates(float * world_coordinates);


#endif /* W3D_H */